version: "3.7"

services:
  sonarqube-postgresql:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./postgres/data:/var/lib/postgresql/data
    restart: always
    container_name: sonarqube-postgresql
    networks:
      - sonarqube_network
  sonarqube-server:
    image: sonarqube:lts
    ports:
      - "9000:9000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./sonarqube/conf:/opt/sonarqube/conf
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/logs:/opt/sonarqube/logs
      - ./sonarqube/extensions:/opt/sonarqube/extensions
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://sonarqube-postgresql:5432/sonar
    restart: always
    container_name: sonarqube-server
    depends_on:
      - sonarqube-postgresql
    networks:
      - sonarqube_network

networks:
  sonarqube_network:
    name: sonarqube
