version: "2"

services:
  gogs:
    image: gogs/gogs:0.11.91
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/data
    ports:
      - "3000:3000"
      - "3022:22"
    restart: always
    container_name: gogs
    networks:
      - gogs_network

networks:
  gogs_network:
    name: gogs
