version: "3.1"

services:
  mongo-db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/data/db
    restart: always
    container_name: mongo-db
    networks:
      - mongo_network

networks:
  mongo_network:
    name: mongo-db
