version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    privileged: true
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - ./data:/usr/share/elasticsearch/data
      - ./conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      #- ./elasticsearch/jvm.options:/usr/share/elasticsearch/config/jvm.options
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: "always"
    container_name: elasticsearch
    networks:
      - elastic_network
networks:
  elastic_network:
    name: elastic

