version: "2.2"

services:
  elasticsearch-head:
    image: mobz/elasticsearch-head:5
    ports:
      - 9100:9100
    container_name: elasticsearch-head
    restart: always
    networks:
      - elasticsearch
      
networks:
  elasticsearch_network:
    name: elasticsearch