version: "2"

services:
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    restart: always
    container_name: portainer
    networks:
      - portainer_network

volumes: 
  portainer:
    name: portainer

networks:
  portainer_network:
    name: portainer
