version: "2.2"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.14
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      # 警用xpack的安全控制，许可证默认30天
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - ./conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    container_name: elasticsearch
    restart: always
    networks:
      - elasticsearch

volumes:
  elasticsearch-data:
    name: elasticsearch-data

networks:
  elasticsearch_network:
    name: elasticsearch
