version: "3.7"

services:
  mysql:
    image: docker.io/mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./conf:/etc/mysql/conf.d
      - ./data:/var/lib/mysql
    restart: always
    container_name: mysql
    networks:
      - mysql_network

networks:
  mysql_network:
    name: mysql
